### ISSUE TITLE
"configFileName" : "apigen.neon",

### ISSUE THREAD

**Issue by leosxie** [dans98/Sublime-ApiGen#1]
when i run apigen generate,
console message:No config file could not be found!

where can i found apigen.neon configfile? or i must write it by myself?

can you show me the file content?

**Comment by dans98** [comment]
The apigen.neon file is something that you must create that is specific to your code base. Basically it tells apigen what to do.

These are some old examples from the apigen source and other places..
https://searchcode.com/codesearch/view/17052062/
https://github.com/gharlan/apigen/blob/develop/apigen.neon.example
