### ISSUE TITLE
destination error

### ISSUE THREAD

**Issue by withoutness** [dans98/Sublime-ApiGen#2]
when i run apigen->generate,
console message: Destination is not set. Use '-d <dir>' or config to set it
here is my apigen.neon file 
source: 
    /mysourcefolder
destination: 
    /somedestionationfolder

what am i doing wrong?

**Comment by dans98** [comment]
This actual apigen not being able to parse your .neon file. 

here is an example file structure i use, and how the apigen.neon file looks.

directory stucture:
projectName/src/{all source files in here}
projectName/tests/{phpunit stuff goes here}
projectName/docs/{all apigen generated files go in here}
projectName/apigen.neon
projectName/composer.json

apigen.neon file:

# Source file or directory to parse

source: '.\src'

# Directory where to save the generated documentation

destination: '.\docs'

# List of allowed file extensions

extensions: [php]

# Mask to exclude file or directory from processing

exclude: []

# Don't generate documentation for classes from file or directory with this mask

skipDocPath:

# Character set of source files

charset: ['UTF-8']

# Main project name prefix

main:

# Title of generated documentation

title: 'The project tittle'

# Documentation base URL

baseUrl:

# Google Custom Search ID

googleCseId:

# Google Analytics tracking code

googleAnalytics:

# Grouping of classes

groups: auto

# Generate documentation for methods and properties with given access level

accessLevels: [public, protected, private]

# Generate documentation for elements marked as internal and display internal documentation parts

internal: Yes

# Generate documentation for PHP internal classes

php: Yes

# Generate tree view of classes, interfaces and exceptions

tree: Yes

# Generate documentation for deprecated classes, methods, properties and constants

deprecated: No

# Generate documentation of tasks

todo: Yes

# Generate highlighted source code files

sourceCode: Yes

# Add a link to download documentation as a ZIP archive

download: No

# Don't display scanning and generating messages

quiet: No

# Display additional information in case of an error

debug: Yes
